# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["Gemfile", "Gemfile.lock"] # files to exclude
highlighter: pygments
markdown: kramdown
#disqus:
#google_analytics:
title: "That Reminds Me"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: That Reminds Me

description: Occasional mind-sparks.
author:
  name: Matthew Richardson
#  email:
  github: mrichar1
#  twitter: dbtek
#  pinterest: asd123
#  linkedin: asd123
#  bio: Your stylish, minimalist theme!
  email_md5: 25d2babd430399ae956344a611d7bc05

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1
sidebar_image: http://www.woodwose.net/woodwose.gif

BASE_PATH:

gems:
  - jekyll-paginate
